### PR TITLE
Update to Apollo 0.2.x

### PR DESCRIPTION
**Pull request by p4bloch**
I think this is important as the (great) video tutorial from @helfer on Apollo's YT channel was my first approach to the tool and it took me a few days to realize that `apolloServer` had evolved into `apolloExpress` and that the `apollo-server` package was the way to go now.

Hope this helps clarifying that the video is a bit outdated (but still _very_ helpful) 🙂

### CODE REVIEW

**Comment by helfer** [comment]
@p4bloch I think rather than updating the code here, it would be better to add a note to the tutorial, saying that the API has changed since 0.1. I still think the 0.1 API is better for the tutorial because it's easier. Since this repo is essentially only used for the tutorial, we should keep it the way it is, so I don't think we should merge your changes

However, I will leave this PR open so other people can find it easily.

@p4bloch do you agree (I'm asking since it seems like you recently did the tutorial, so you would know better than me if/how it should be updated).

**Comment by p4bloch** [comment]
@helfer I agree that consistency between the video tutorial and the code must be kept, and that 0.1 API is easier to grasp.

In my experience (I was learning the concepts of GraphQL and how Apollo fit in there) your tutorial was extremely clarifying, and as a result, I used that to show off what Apollo did in an [introductory talk](https://www.youtube.com/watch?v=yvjABpL0O2M) I gave at a meetup group and never found out that there even was a new version of Apollo in my (not so good) research. No big deal, of course, but I was really into learning Apollo and took your video for granted.

So, absolutely :+1: to adding a note to the video, but it would also be helpful to provide the code somewhere so people can play around with the updated API and easily understand the concepts they already learnt with you.

Maybe we could merge this into a new branch and add a note to the README on master as well so it can be found easier.

**Comment by helfer** [comment]
@p4bloch Yeah, we can definitely merge it into a separate branch, but I wonder what that would be good for, because there's virtually no way to update the tutorial. The only thing that might make sense is to add a step at the end where we take people from apollo-server v1 to v2 so their entire app now works on Apollo Server V2. Do you think that would make sense?

**Comment by p4bloch** [comment]
IMHO what would definitely add value to this is to somehow let the user know that the `apollo-server` version is not the latest one. If that links to an updated codebase like the one I suggest in this PR, the better, but the fact that such message was not in the README was the missing step in my learning process.

I don't think the tutorial needs updating, the concepts are really well explained and the changes in the new version are not that relevant, it's just that whoever clones this repo should be aware that this version is not the latest one.

**Comment by helfer** [comment]
I've edited the readme, do you think it looks okay now?

**Comment by p4bloch** [comment]
@helfer perfect! 🎉

**Pull request closed without merging**
